server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SERVICE_CURSOS?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

auth:
  username: admin
  password: admin123

jwt:
  secret: "87be503d4da541e97a4368e431ab72df45b65caa"
  expirationMillis: 3600000
